#+OPTIONS: ^:nil

* rustup
#+begin_src shell
  rustup update
  rustup doc --book
#+end_src
* cargo
#+begin_src shell
  cargo run
  cargo run -p adder
  RUST_BACKTRACE=1 cargo run --verbose
  RUST_BACKTRACE=full cargo run

  cargo build --verbose

  cargo update

  cargo doc          # calls rustdoc
  cargo doc --open

  cargo login [token]
  cargo publish
  cargo yank --vers 1.0.1
  cargo yank --vers 1.0.1 --undo

  cargo install

  cargo --list
#+end_src
* cargo test
#+begin_src shell
  cargo test -- --test-threads=1
  cargo test -- --show-output
  cargo test <test_function_name>
  cargo test <sub_string_of_test_names_including_module_names_plus_function_names>
  cargo test -- --ignored
  cargo test --test <integration_test's crate_name or function_name>
  cargo test -p <crate in a workspace>
  cargo test --features <feature_name>  # for #[cfg(feature = "feature_name")]
#+end_src

  In the *<proj_root>/tests/* directory, Cargo will compile each of the files as
  an individual crate.

  Files in subdirectories of the tests directory don’t get compiled as separate
  crates or have sections in the test output.

  Common test files must be put in subdirectories, each directory represents a
  module.  For example, to use "common" module, put the code for common module
  in *<proj_root>/tests/common/mod.rs*.  If we rename mod.rs to other name,
  Cargo won't be able to find the module definition, because there is no
  *<proj_root>/tests/common.rs* as a guide.
* rustc
#+begin_src shell
  rustc --explain E0308
#+end_src
* macros
#+begin_verse
#[derive(Clone, PartialEq, Debug)]
#![allow(unused)]
unimplemented!()
#[cfg(test)]
#[test]
println!
unimplemented!
#+end_verse
* THOUGHTS
** Don't abuse variable shadowing.
#+begin_quote
  This feature is often used in situations in which you want to convert a value
  from one type to another type.  Shadowing lets us reuse the 'guess' variable
  name rahter than forcing us to create two unique variables, such as
  'guess_str' and 'guess' for example.
#+end_quote
  However, it makes people hard to find its definition.  Let's see if tools can
  help find the accurate definition in one go.
** Don't use the "return value" of an operation.
#+begin_src rust
  let mut y = 5;
  let x = (y = 6);		// x has the value '()', not '6'
#+end_src
  This feature is to make sure that every expression to have a value, including
  the assignment operation/expression.

  The fundamental design fault is that they use an empty tuple to denote a void
  type.

  Rust allows you to propogate a meaningless return type of an statement like
  expression.  If this kind of error is not caught and is propogated to other
  places, it will be difficult to find the root cause, and this issue may cause
  runtime errors or type checking errors.

  The same design fault lives in JavaScript and PHP where the meaningless
  "undefined" is spreaded over the whole program.
** A good example of the use of enum type (union type) to enfoce exception handling
#+begin_src shell
   Compiling guessing-game v0.1.0 (/Users/rduan/mygitlab/study-rust/guessing-game)
error[E0308]: mismatched types
  --> src/main.rs:20:22
   |
20 |     let guess: u32 = guess.trim().parse();//.expect("Please type a number!");
   |                ---   ^^^^^^^^^^^^^^^^^^^^ expected `u32`, found enum `Result`
   |                |
   |                expected due to this
   |
   = note: expected type `u32`
              found enum `Result<_, _>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `guessing-game`

To learn more, run the command again with --verbose.
#+end_src
* Print type of a variable
#+begin_src rust
  fn print_type_of<T>(_: &T) {
      println!("{}", std::any::type_name::<T>())
  }
#+end_src
* &[String], &Vec<String> and [String; 5]
  [String; 5] is a primitive array type.

  &[String] is a slice, it can be a slice of a vector or an array, etc.

  &Vec<String> is a reference of Vec<String>.
* Reasons to adopt Rust in our projects
  - advanced tool to aid us to design and code
    - type safety
      - no the billion-dollar bug (null bug)
      - safer error handling than Go and other nullable language, compiler can
        aid us and protect us
    - easy concurrency and reasoning (human understanding) by declarative
      computing
      - immutable variable by default
      - support closure which facilitates functional programming paradigm
    - modern built-in types and types from the standard library (using old
      languages, we have to tweak the old types for good practices nowadays)
  - prototyping and enough optimization in one go, compared to quick
    prototyping and hard and long optimization in Python
  - save cloud cost by
    - extremely high runtime speed (can serve more requests per second)
      comparable to C/C++
    - small memory footprints
    - small container images
  - modern tooling
    - very helpful compiler
    - specialized build system included (i.e. cargo) vs. C++'s GNU Make
    - documentation tools (e.g. rustup doc)
    - good test framework to support TDD
    - modern package and module system (good trade-off between conventions and
      flexibility)
  - expressive and concise
    - less boilerplate code than Java and C++
    - more expressive and elegant than Go
      - support Generic
	- consider a use case where we need to sort entries of a user defined
          type, Go's implementation is tedious
	- In Go, people tend to abuse interface{} to hold unknown type of data,
          which bypasses the type safety checking
      - better trade-off than Go
        - Go hard-codes hash table into the language, whereas Rust uses library
  - modern package and module management
  - good community
    - strong language developers
    - friendly and supportive
    - backing from large companies (Mozilla, Microsoft, Amazon, Google, etc.)
  - better FFI than Go
* Cons compared to Python
  - no REPL
  - harder to learn
  - burden to manipulate the object memory ownership
  - less mature in the ecosystem
  - a little less coding speed
* Cons compared to Swift
  - no REPL
  - syntax being more elaborate
* Cons compared to C++
  - less mature in the ecosystem
* Cons compared to Java 8
  - less mature in the ecosystem
* Cons compared to Go
  - less mature in the ecosystem
  - harder to learn
* Cons compared to Common Lisp
  - no REPL
  - harder to use macros, so harder to implement "data as code" and "code as data"
* Compare with Oz
** pros
   - much better string type
   - better runtime performance
   - smaller memory footprint, e.g. functions don't capture context variables
** cons
   - no tail call optimization which leads to a crippled support for recursion,
     which leads to less descriptive programming paradigm.
   - tedious to express recursive types (structures), such as linked list,
     trees, and graphs, unless using raw pointers.  This is due to lack of GC.
   - no difference list
   - conceptually more complicated types for pattern matching.  In Oz, Record
     type suffices.
   - quirks due to the expression-based design
     I like Oz's design better: procedure and functions are different types.
     e.g.
     - operations return an empty tuple
     - placing a semicolon turns an expression to a statement
   - functions are not closures, so the functional programming is limited
   - due to ownership rules and lack of GC, closures are complicated: it either
     borrows or moves captured values
* Compared with Swift
https://dev.to/rhymu8354/swift-vs-rust-an-overview-of-swift-from-a-rusty-perspective-18c7
* It is a design error to use an empty tuple to denote the Void type
  I like the Oz's design: an operation does not return anything.
* ANSI colors
#+begin_src rust
  const ANSI_BLACK: &str = "\x1b[0;30m";
  const ANSI_RED: &str = "\x1b[0;31m";
  const ANSI_GREEN: &str = "\x1b[0;32m";
  const ANSI_YELLOW: &str = "\x1b[0;33m";
  const ANSI_BLUE: &str = "\x1b[0;34m";
  const ANSI_MAGENTA: &str = "\x1b[0;35m";
  const ANSI_CYAN: &str = "\x1b[0;36m";
  const ANSI_WHITE: &str = "\x1b[0;37m";
  const ANSI_RESET: &str = "\x1b[0m";
#+end_src
* Idioms
** Open file and read to string
The following four versions are equivalent.

#+begin_src rust
  // Version 1
  use std::fs;
  use std::io;

  fn read_username_from_file() -> Result<String, io::Error> {
      fs::read_to_string("hello.txt")
  }
#+end_src

#+begin_src rust
  // Version 2
  use std::fs::File;
  use std:io;
  use std::io::Read;

  fn read_username_from_file() -> Result<String, io::Error> {
      let mut s = String::new();
      File::open("hello.txt")?.read_to_string(&mut s)?;
      Ok(s)
  }
#+end_src

#+begin_src rust
  // Version 3
  use std::fs::File;
  use std::io;
  use std::io::Read;

  fn read_username_from_file() -> Result<String, io::Error> {
      let mut f = File::open("hello.txt")?;
      let mut s = String::new();
      f.read_to_string(&mut s)?;
      Ok(s)
  }
#+end_src

#+begin_src rust
  // Version 4
  use std::fs::File;
  use std::io;
  use std::io::Read;

  fn read_username_from_file() -> Result<String, io::Error> {
      let f = File::open("hello.txt");

      let mut f = match f {
	  Ok(file) => file,
	  Err(e) => return Err(e),
      };

      let mut s = String::new();

      match f.read_to_string(&mut s) {
	  Ok(_) => Ok(s),
	  Err(e) => Err(e),
      }
  }
#+end_src
** Return Ok(()) to indicate that the call is for its side effects only
** Return `Result<(), Box<dyn Error>>` for general run() method
** How to specify the Fn trait bounds
   Most of the time when specifying one of the Fn trait bounds, you can start
   with Fn and the compiler will tell you if you need FnMut or FnOnce based on
   what happens in the closure body.
** Compile time polymorphism (static dispatch): bounded parametric polymorphism
   *Generics* and *Trait bounds* is preferable for homogeneous collections,
   because the definitions will be /monomorphized/ at compile time to use the
   concret types.
#+begin_src rust
  pub struct Screen<T: Draw> {
      // The vector can hold only one type of objects, such as Button or TextField.
      pub components: Vec<T>,
  }

  impl<T> Screen<T>
  where
      T: Draw,
  {
      pub fn run(&self) {
	  for component in self.components.iter() {
	      component.draw();
	  }
      }
  }
#+end_src
** Run time polymorphism (duck typing, dynamic dispatch): trait object
   It is like a C++ object which binds behaviors with data.  In C++, the
   dynamic behaviors are implemented by a virtual table in an object.  In a
   Rust's trait object, such kind of virtual table is also embedded.
#+begin_src rust
  pub trait Draw {
      fn draw(&self);
  }

  pub struct Screen {
      // The vector can hold any objects that implements the `Draw` trait,
      // such as Box<Button> and Box<TextField>.
      pub components: Vec<Box<dyn Draw>>,
  }
#+end_src
*** Pros compared to duck typing in dynamically typed languages
#+begin_quote
The advantage of using trait objects and Rust’s type system to write code
similar to code using duck typing is that we never have to check whether a
value implements a particular method at runtime or worry about getting errors
if a value doesn’t implement a method but we call it anyway. Rust won’t compile
our code if the values don’t implement the traits that the trait objects need.
#+end_quote
*** Pros compared to closures as objects
    A closure can binds data and behaviors together, thus it can be used as an
    `object`.  However, it is not easy to tell what type of object it is, for
    example, whether it implements `draw()` method or not.

    Duck typing in dynamically typed languages is implemented in a similar way
    as closures.
** Use enum to let Vec<T> hold limited different types
#+begin_src rust
  enum SpreadsheetCell {
      Int(i32),
      Float(f64),
      Text(String),
  }

  let row = vec![
      SpreadsheetCell::Int(3),
      SpreadsheetCell::Text(String::from("blue")),
      SpreadsheetCell::Float(10.12),
  ];
#+end_src
** Option<T>
#+begin_src rust
  option.expect()
  option.take()
  option.as_ref()
  option.is_some()
  option.is_none()
  option.unwrap()
#+end_src
* Vector to HashSet
#+begin_src rust
    let set: std::collections::HashSet<&str> =
        ["hello", "€a", "banana", "a⬂"].iter().cloned().collect();
#+end_src
* Cautions
** std::process::exit()
   https://doc.rust-lang.org/std/process/fn.exit.html

   [[https://users.rust-lang.org/t/is-rust-cleaning-up-after-exit/9613][Is Rust Cleaning Up After Exit]]
** str::to_lowercase is not 100% accurate
From the Rust book:
#+begin_quote
While to_lowercase will handle basic Unicode, it won't be 100% accurate.  If we
were writing a real application, we'd want to do a bit more work here.
#+end_quote
