[package]
name = "guessing-game"
version = "0.1.0"
authors = ["Rui Duan <rui.duan@loblaw.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
